/**
 * lucide-static パッケージから全アイコンの SVG パスデータを抽出し、
 * src/icons/iconData.ts を再生成するスクリプト
 *
 * 使用方法:
 *   npx tsx scripts/generate-icon-data.ts
 *
 * 前提:
 *   npm install --save-dev lucide-static
 */

import * as fs from "node:fs";
import { createRequire } from "node:module";
import * as path from "node:path";

const require = createRequire(import.meta.url);

// lucide-static のパッケージルートを解決
let lucidePkgPath: string;
try {
  lucidePkgPath = require.resolve("lucide-static/package.json");
} catch {
  console.error(
    "lucide-static が見つかりません。npm install --save-dev lucide-static を実行してください。",
  );
  process.exit(1);
}

const lucideRoot = path.dirname(lucidePkgPath);
const iconsDir = path.join(lucideRoot, "icons");

// lucide-static の package.json からバージョンを取得
const lucidePkg = JSON.parse(fs.readFileSync(lucidePkgPath, "utf-8"));
const version: string = lucidePkg.version;

// 全 SVG ファイルを読み込み
const svgFiles = fs
  .readdirSync(iconsDir)
  .filter((f) => f.endsWith(".svg"))
  .sort();

const iconData: Record<string, string> = {};
for (const file of svgFiles) {
  const name = file.replace(".svg", "");
  const svg = fs.readFileSync(path.join(iconsDir, file), "utf-8");
  const match = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!match) {
    throw new Error(`SVG パスデータの抽出に失敗しました: ${file}`);
  }
  iconData[name] = match[1].trim();
}

// 件数の整合性を検証
if (Object.keys(iconData).length !== svgFiles.length) {
  throw new Error(
    `アイコン件数が不一致: SVGファイル ${svgFiles.length} 件, 抽出成功 ${Object.keys(iconData).length} 件`,
  );
}

// TypeScript ファイルを生成
let content = `// Auto-generated from lucide-static v${version} (ISC License)\n`;
content += "// https://lucide.dev/\n";
content += `// Generated by: npx tsx scripts/generate-icon-data.ts\n`;
content += `// Total icons: ${Object.keys(iconData).length}\n\n`;
content += "export const ICON_DATA: Record<string, string> = {\n";

for (const [name, data] of Object.entries(iconData)) {
  // バッククォート内のバッククォートをエスケープ
  const escaped = data.replace(/`/g, "\\`").replace(/\$/g, "\\$");
  content += `  "${name}": \`${escaped}\`,\n`;
}

content += "};\n";

const rootDir = path.resolve(import.meta.dirname!, "..");
const outputPath = path.join(rootDir, "src", "icons", "iconData.ts");
fs.writeFileSync(outputPath, content);

console.log(`Generated ${outputPath}`);
console.log(`  lucide-static version: v${version}`);
console.log(`  Total icons: ${Object.keys(iconData).length}`);
console.log(
  `  File size: ${(fs.statSync(outputPath).size / 1024).toFixed(1)} KB`,
);
